#!/usr/bin/env python3
# John Vidale 4/2020

import os
os.environ['PATH'] += os.pathsep + '/usr/local/bin'
os.chdir('/Users/vidale/Documents/GitHub/Array_codes')

#%% Import functions
from run_each_C_PKiKP import run_each
from run_each_J_PcP import run_eachPcP
from run_each_J_ICS import run_eachICS

#run_each(start_buff = 3.0,   end_buff = 5.5,   event_no = 201, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  1.0,   end_buff = 3.0,   event_no = 202, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 4.0,   end_buff = 7.0,   event_no = 203, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 1.5,   end_buff = 4.0,   event_no = 204, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 2.0,   end_buff = 4.3,   event_no = 205, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 0.0,   end_buff = 3.0,   event_no = 206, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 3.0,   end_buff = 7.0,   event_no = 207, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 208, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 209, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 210, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 211, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 212, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 213, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 214, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 215, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 216, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 217, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 218, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 219, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 220, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 220, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 221, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 222, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 223, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 224, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 225, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 226, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff =  -5,   end_buff = 10,   event_no = 227, rel_time = 1, dphase = 'PKiKP')

run_each(start_buff = 40,   end_buff = 100,   event_no = 201, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 201, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 202, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 203, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 204, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 205, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 206, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 207, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 208, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 210, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 211, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 212, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 213, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 214, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 215, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 216, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 217, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 218, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 219, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 220, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 220, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 221, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 222, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 223, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 224, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 225, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 226, rel_time = 1, dphase = 'PKiKP')
#run_each(start_buff = 40,   end_buff = 100,   event_no = 227, rel_time = 1, dphase = 'PKiKP')
